apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: webviz
spec:
  build:
    useBuildKit: true
  environments:
    - name: prod
    - name: preprod
      build:
        from: main
    - name: review
      build:
        from: review
    - name: review2
      build:
        from: review2
    - name: dev
      build:
        from: dev

  components:
    # -----------------------------------------------------------------
    - name: frontend
      dockerFileName: frontend-prod.Dockerfile
      publicPort: http
      ports:
        - name: http
          port: 8080
      network:
        ingress:
          public:
            proxyReadTimeout: 120


    # -----------------------------------------------------------------
    - name: backend-primary
      dockerFileName: ./backend_py/primary/Dockerfile
      ports:
        - name: http
          port: 5000
      # Set non-prod clientId and client secret as default, prod overrides below
      identity:
        azure:
          clientId: 025fe044-5ee8-4b27-bf83-aefb548f14fa
      secretRefs:
        azureKeyVaults:
          - name: kv-webviz-shared
            useAzureIdentity: true
            items:
              - { name: webviz-client-secret-nonprod, envVar: WEBVIZ_CLIENT_SECRET }
              - { name: webviz-smda-subscription-key, envVar: WEBVIZ_SMDA_SUBSCRIPTION_KEY }
              - { name: webviz-enterprise-subscription-key, envVar: WEBVIZ_ENTERPRISE_SUBSCRIPTION_KEY }
              - { name: webviz-pseudonym-hmac-key, envVar: WEBVIZ_PSEUDONYM_HMAC_KEY }
              - { name: webviz-session-store-fernet-key, envVar: WEBVIZ_SESSION_STORE_FERNET_KEY }
              - { name: webviz-redis-auth-store-password, envVar: WEBVIZ_REDIS_AUTH_STORE_PASSWORD }
              - { name: webviz-redis-cache-password, envVar: WEBVIZ_REDIS_CACHE_PASSWORD }
              # Inject all App Insights connection strings as env vars.
              # Azure Monitor setup picks the right one based on the Radix environment.
              - { name: webviz-insights-connectionstring-prod, envVar: WEBVIZ_INSIGHTS_CONNECTIONSTRING_PROD }
              - { name: webviz-insights-connectionstring-preprod, envVar: WEBVIZ_INSIGHTS_CONNECTIONSTRING_PREPROD }
              - { name: webviz-insights-connectionstring-dev, envVar: WEBVIZ_INSIGHTS_CONNECTIONSTRING_DEV }
              - { name: webviz-insights-connectionstring-review, envVar: WEBVIZ_INSIGHTS_CONNECTIONSTRING_REVIEW }
      variables:
        UVICORN_PORT: 5000
        WEBVIZ_VDS_HOST_ADDRESS: "https://server-oneseismic-prod.radix.equinor.com"
        WEBVIZ_DUMMY_OPERATION_GENERATION: 123
      environmentConfig:
        - environment: prod
          identity:
            azure:
              # Override with prod clientId
              clientId: 900ed417-a860-4970-bd37-73b059ca6f0d
          secretRefs:
            azureKeyVaults:
              - name: kv-webviz-shared
                useAzureIdentity: true
                items:
                  - { name: webviz-client-secret-prod, envVar: WEBVIZ_CLIENT_SECRET }
          resources:
            requests:
              memory: 8Gi
              cpu: 1000m
            limits:
              # Memory limit=request and cpu limit omitted on purpose
              memory: 8Gi
          horizontalScaling:
            minReplicas: 2
            maxReplicas: 4
            resources:
              memory:
                averageUtilization: 60
              cpu:
                averageUtilization: 80

        - environment: preprod
          resources:
            requests:
              memory: 4Gi
              cpu: 500m
            limits:
              memory: 4Gi
          horizontalScaling:
            minReplicas: 1
            maxReplicas: 3
            resources:
              memory:
                averageUtilization: 60
              cpu:
                averageUtilization: 80

        - environment: review
          resources:
            requests:
              memory: 4Gi
              cpu: 500m
            limits:
              memory: 4Gi
          horizontalScaling:
            minReplicas: 1
            maxReplicas: 3
            resources:
              memory:
                averageUtilization: 60
              cpu:
                averageUtilization: 80

        - environment: dev
          resources:
            requests:
              memory: 4Gi
              cpu: 500m
            limits:
              memory: 4Gi
          horizontalScaling:
            minReplicas: 1
            maxReplicas: 3
            resources:
              memory:
                averageUtilization: 60
              cpu:
                averageUtilization: 80


    # -----------------------------------------------------------------
    - name: surface-query
      dockerFileName: ./backend_go/surface_query/Dockerfile.prod
      ports:
        - name: http
          port: 5001
      variables:
        SURFACE_QUERY_SERVER_MODE: syncserver
      resources:
        requests:
          memory: 8Gi
          cpu: 2000m
        limits:
          # Even though the general advice is to leave cpu limit unspecified, here we set it to the same as requests.
          # As of now, it seems that it's the cpu limit value that will be picked up by automaxprocs utilized in the go service.
          memory: 8Gi
          cpu: 2000m
      horizontalScaling:
        minReplicas: 1
        maxReplicas: 4
        pollingInterval: 15
        triggers:
        - name: cpu
          cpu:
            value: 20
        - name: memory
          memory:
            value: 20


    # -----------------------------------------------------------------
    - name: redis-auth-store
      dockerFileName: ./docker/redis/Dockerfile
      identity:
        azure:
          # Set nonprod clientId as default, prod overrides below
          clientId: 025fe044-5ee8-4b27-bf83-aefb548f14fa
      secretRefs:
        azureKeyVaults:
          - name: kv-webviz-shared
            useAzureIdentity: true
            items:
              - { name: webviz-redis-auth-store-password, envVar: REDIS_REQUIREPASS }
      runAsUser: 999
      args: ["--maxmemory", "800mb",  "--maxmemory-policy", "noeviction", "--loglevel", "notice"]
      ports:
        - name: http
          port: 6379
      resources:
        requests:
          memory: 1Gi
          cpu: 500m
        limits:
          memory: 1Gi
      environmentConfig:
        - environment: prod
          identity:
            azure:
              # Override with prod clientId
              clientId: 900ed417-a860-4970-bd37-73b059ca6f0d


    # -----------------------------------------------------------------
    - name: redis-cache
      dockerFileName: ./docker/redis/Dockerfile
      identity:
        azure:
          # Set nonprod clientId as default, prod overrides below
          clientId: 025fe044-5ee8-4b27-bf83-aefb548f14fa
      secretRefs:
        azureKeyVaults:
          - name: kv-webviz-shared
            useAzureIdentity: true
            items:
              - { name: webviz-redis-auth-store-password, envVar: REDIS_REQUIREPASS }
      runAsUser: 999
      # https://redis.io/docs/latest/operate/oss_and_stack/management/config/#configuring-redis-as-a-cache
      # maxmemory for redis must be aligned with component's requested memory, here 3gb vs 4gb
      args: ["--maxmemory", "3gb",  "--maxmemory-policy", "allkeys-lru",  "--loglevel", "notice"]
      ports:
        - name: http
          port: 6379
      resources:
        requests:
          memory: 4Gi
          cpu: 1000m
        limits:
          memory: 4Gi
      environmentConfig:
        - environment: prod
          identity:
            azure:
              # Override with prod clientId
              clientId: 900ed417-a860-4970-bd37-73b059ca6f0d


  jobs:
    # -----------------------------------------------------------------
    - name: user-mock
      dockerFileName: ./backend_py/user_mock/Dockerfile
      schedulerPort: 8001
      ports:
        - name: http
          port: 8001
      variables:
        UVICORN_PORT: 8001

    # -----------------------------------------------------------------
    - name: user-grid3d-ri
      dockerFileName: ./backend_py/user_grid3d_ri/Dockerfile
      schedulerPort: 8002
      ports:
        - name: http
          port: 8002
      identity:
        azure:
          # Set nonprod clientId as default, prod overrides below
          clientId: 025fe044-5ee8-4b27-bf83-aefb548f14fa
      secretRefs:
        azureKeyVaults:
          - name: kv-webviz-shared
            useAzureIdentity: true
            items:
              # Inject all App Insights connection strings as env vars.
              # Azure Monitor setup picks the right one based on the Radix environment.
              - { name: webviz-insights-connectionstring-prod, envVar: WEBVIZ_INSIGHTS_CONNECTIONSTRING_PROD }
              - { name: webviz-insights-connectionstring-preprod, envVar: WEBVIZ_INSIGHTS_CONNECTIONSTRING_PREPROD }
              - { name: webviz-insights-connectionstring-dev, envVar: WEBVIZ_INSIGHTS_CONNECTIONSTRING_DEV }
              - { name: webviz-insights-connectionstring-review, envVar: WEBVIZ_INSIGHTS_CONNECTIONSTRING_REVIEW }
      variables:
        UVICORN_PORT: 8002
      payload:
        path: /compute/args
      environmentConfig:
        - environment: prod
          identity:
            azure:
              # Override with prod clientId
              clientId: 900ed417-a860-4970-bd37-73b059ca6f0d

  dnsAppAlias:
    environment: prod
    component: frontend
  dnsExternalAlias:
    - alias: webviz.fmu.equinor.com
      component: frontend
      environment: prod
      useCertificateAutomation: true
