export enum CustomDataProviderType {
    OBSERVED_SURFACE = "OBSERVED_SURFACE",
    REALIZATION_SURFACE = "REALIZATION_SURFACE",
    STATISTICAL_SURFACE = "STATISTICAL_SURFACE",
    REALIZATION_POLYGONS = "REALIZATION_POLYGONS",
    REALIZATION_GRID = "REALIZATION_GRID",
}
