import "./DbgWorkbenchSpy/registerModule";
import "./DistributionPlot/registerModule";
import "./InplaceVolumetrics/registerModule";
import "./Map/registerModule";
import "./MyModule2/registerModule";
import "./MyModule/registerModule";
import "./SimulationTimeSeries/registerModule";
import "./Table/registerModule";
import "./TimeSeriesParameterDistribution/registerModule";
