import "./DbgWorkbenchSpy/registerModule";
import "./DistributionPlot/registerModule";
import "./Grid3D/registerModule";
import "./Grid3DIntersection/registerModule";
import "./InplaceVolumetrics/registerModule";
import "./Map/registerModule";
import "./MyModule2/registerModule";
import "./MyModule/registerModule";
import "./SimulationTimeSeries/registerModule";
import "./TimeSeriesParameterDistribution/registerModule"
import "./Grid3D/registerModule"
import "./Grid3DIntersection/registerModule"
import "./Pvt/registerModule"
import "./Sensitivity/registerModule"
import "./SimulationTimeSeriesSensitivity/registerModule"