import "./MyModule2/registerModule";
import "./MyModule/registerModule";
import "./SimulationTimeSeries/registerModule";
import "./InplaceVolumetrics/registerModule";
import "./Map/registerModule";
import "./DbgWorkbenchSpy/registerModule";
import "./TimeSeriesParameterDistribution/registerModule"
import "./Grid3D/registerModule"
import "./Grid3DIntersection/registerModule"
import "./Pvt/registerModule"
import "./SeismicSurfaceAttributes/registerModule"