export enum DataProviderType {
    DRILLED_WELLBORE_PICKS = "DRILLED_WELLBORE_PICKS",
    DRILLED_WELL_TRAJECTORIES = "DRILLED_WELL_TRAJECTORIES",
    INTERSECTION_WITH_WELLBORE_EXTENSION_REALIZATION_GRID = "INTERSECTION_WITH_WELLBORE_EXTENSION_REALIZATION_GRID",
    INTERSECTION_REALIZATION_OBSERVED_SEISMIC = "INTERSECTION_REALIZATION_OBSERVED_SEISMIC",
    INTERSECTION_REALIZATION_SIMULATED_SEISMIC = "INTERSECTION_REALIZATION_SIMULATED_SEISMIC",
    INTERSECTION_REALIZATION_GRID = "INTERSECTION_REALIZATION_GRID",
    REALIZATION_POLYGONS = "REALIZATION_POLYGONS",
    REALIZATION_SURFACE = "REALIZATION_SURFACE",
    REALIZATION_SURFACE_3D = "REALIZATION_SURFACE_3D",
    STATISTICAL_SURFACE = "STATISTICAL_SURFACE",
}
