export enum SettingType {
    ENSEMBLE = "ensemble",
    REALIZATION = "realization",
    STATISTIC_FUNCTION = "statisticFunction",
    SENSITIVITY = "sensitivity",
    SURFACE_NAME = "surfaceName",
    ATTRIBUTE = "attribute",
    TIME_OR_INTERVAL = "timeOrInterval",
    POLYGONS_ATTRIBUTE = "polygonsAttribute",
    POLYGONS_NAME = "polygonsName",
    SMDA_WELLBORE_HEADERS = "smdaWellboreHeaders",
    GRID_NAME = "gridName",
    GRID_LAYER_I_RANGE = "gridLayerIRange",
    GRID_LAYER_J_RANGE = "gridLayerJRange",
    GRID_LAYER_K_RANGE = "gridLayerKRange",
    GRID_LAYER_K = "gridLayerK",
    SHOW_GRID_LINES = "showGridLines",
    SEISMIC_INLINE = "seismicInline",
    SEISMIC_CROSSLINE = "seismicCrossline",
    SEISMIC_DEPTH_SLICE = "seismicDepthSlice",
}
