export enum CustomDataProviderType {
    REALIZATION_SEISMIC_CROSSLINE = "REALIZATION_SEISMIC_CROSSLINE",
    REALIZATION_SEISMIC_INLINE = "REALIZATION_SEISMIC_INLINE",
    REALIZATION_SEISMIC_DEPTH_SLICE = "REALIZATION_SEISMIC_DEPTH_SLICE",
}
