export enum CustomDataProviderType {
    REALIZATION_SEISMIC_INLINE = "REALIZATION_SEISMIC_INLINE",
    REALIZATION_SEISMIC_CROSSLINE = "REALIZATION_SEISMIC_CROSSLINE",
    REALIZATION_SEISMIC_DEPTH = "REALIZATION_SEISMIC_DEPTH",
    REALIIZATION_GRID_3D = "REALIZATION_GRID_3D",
}
