export enum LayerType {
    DRILLED_WELLBORE_PICKS = "DRILLED_WELLBORE_PICKS",
    DRILLED_WELL_TRAJECTORIES = "DRILLED_WELL_TRAJECTORIES",
    REALIZATION_GRID = "REALIZATION_GRID",
    REALIZATION_SURFACE = "REALIZATION_SURFACE",
    REALIZATION_POLYGONS = "REALIZATION_POLYGONS",
    REALIZATION_SEISMIC_DEPTH_SLICE = "REALIZATION_SEISMIC_DEPTH_SLICE",
    REALIZATION_SEISMIC_INLINE = "REALIZATION_SEISMIC_INLINE",
    REALIZATION_SEISMIC_CROSSLINE = "REALIZATION_SEISMIC_CROSSLINE",
    OBSERVED_SURFACE = "OBSERVED_SURFACE",
    INTERSECTION_REALIZATION_GRID = "INTERSECTION_REALIZATION_GRID",
    STATISTICAL_SURFACE = "STATISTICAL_SURFACE",
}
