export enum CustomDataProviderType {
    ENSEMBLE_WELLBORE_PICKS = "ENSEMBLE_WELLBORE_PICKS",
    INITIAL_FLUID_CONTACT_SURFACES = "INITIAL_FLUID_CONTACT_SURFACES",
    REALIZATION_SURFACES = "REALIZATION_SURFACES",
    SURFACES_REALIZATIONS_UNCERTAINTY = "SURFACES_REALIZATIONS_UNCERTAINTY",
}
