export const inplaceVolumeAbbreviations: Record<string, { label: string; unit?: string; eclsum?: string[] }> = {
    BULK_OIL: { label: "Bulk volume (oil zone)" },
    BULK_GAS: { label: "Bulk volume (gas zone)" },
    BULK_TOTAL: { label: "Bulk volume (total)" },
    NET_OIL: { label: "Net volume (oil zone)" },
    NET_GAS: { label: "Net volume (gas zone)" },
    NET_TOTAL: { label: "Net volume (total)" },
    PORV_OIL: { label: "Pore volume (oil zone)" },
    PORV_GAS: { label: "Pore volume (gas zone)" },
    PORV_TOTAL: { label: "Pore volume (total)" },
    PORE_OIL: { label: "Pore volume (oil zone)" },
    PORE_GAS: { label: "Pore volume (gas zone)" },
    PORE_TOTAL: { label: "Pore volume (total)" },
    HCPV_OIL: { label: "Hydro carbon pore volume (oil zone)" },
    HCPV_GAS: { label: "Hydro carbon pore volume (gas zone)" },
    HCPV_TOTAL: { label: "Hydro carbon pore volume (total zone)" },
    STOIIP_OIL: { label: "Stock tank oil initially in place (oil zone)" },
    STOIIP_GAS: { label: "Stock tank oil initially in place (gas zone)" },
    STOIIP_TOTAL: { label: "Stock tank oil initially in place (total)" },
    GIIP_OIL: { label: "Gas initially in place (oil zone)" },
    GIIP_GAS: { label: "Gas initially in place (gas zone)" },
    GIIP_TOTAL: { label: "Gas initially in place (total)" },
    RECOVERABLE_OIL: { label: "Recoverable volume (oil zone)" },
    RECOVERABLE_GAS: { label: "Recoverable volume (gas zone)" },
    RECOVERABLE_TOTAL: { label: "Recoverable volume (total)" },
    BULK: { label: "Bulk volume" },
    NET: { label: "Net volume" },
    PORV: { label: "Pore volume" },
    HCPV: { label: "Hydro carbon pore volume" },
    STOIIP: { label: "Stock tank oil initially in place" },
    GIIP: { label: "Gas initially in place" },
    RECOVERABLE: { label: "Recoverable volume" },
    ASSOCIATEDGAS: { label: "Associated gas" },
    ASSOCIATEDOIL: { label: "Associated oil" },
    PORO: { label: "Porosity" },
    SW: { label: "Water saturation" },
    NTG: { label: "Net to gross" },
    BO: { label: "Oil formation volume factor" },
    BG: { label: "Gas formation volume factor" },
};
