// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by generate-tutorials-manifest CLI from metadata declared in tests/e2e/stories/*.test.ts

export type TutorialVideo = {
    slug: string;
    category: string;
    title: string;
    description: string;
    videoUrl: string;
    thumbnailUrl: string;
    stepsUrl: string;
};

export const TUTORIAL_VIDEOS: TutorialVideo[] = [
    {
        slug: "session-and-ensemble-selection",
        category: "Framework",
        title: "Create a session and select an ensemble",
        description: "Start a new session and add a Drogon ensemble to it.",
        videoUrl: "https://webviz.blob.core.windows.net/tutorial-videos/session-and-ensemble-selection.webm",
        thumbnailUrl: "https://webviz.blob.core.windows.net/tutorial-videos/session-and-ensemble-selection.png",
        stepsUrl: "https://webviz.blob.core.windows.net/tutorial-videos/session-and-ensemble-selection.steps.json",
    },
    {
        slug: "grid3d-viewer-3d-grid-model",
        category: "Modules",
        title: "3D Viewer",
        description: "Add the 3D Viewer module to a session.",
        videoUrl: "https://webviz.blob.core.windows.net/tutorial-videos/grid3d-viewer-3d-grid-model.webm",
        thumbnailUrl: "https://webviz.blob.core.windows.net/tutorial-videos/grid3d-viewer-3d-grid-model.png",
        stepsUrl: "https://webviz.blob.core.windows.net/tutorial-videos/grid3d-viewer-3d-grid-model.steps.json",
    },
    {
        slug: "simulation-time-series-chart",
        category: "Modules",
        title: "Simulation Time Series",
        description: "Add the Simulation Time Series module.",
        videoUrl: "https://webviz.blob.core.windows.net/tutorial-videos/simulation-time-series-chart.webm",
        thumbnailUrl: "https://webviz.blob.core.windows.net/tutorial-videos/simulation-time-series-chart.png",
        stepsUrl: "https://webviz.blob.core.windows.net/tutorial-videos/simulation-time-series-chart.steps.json",
    },
];
